### ISSUE TITLE
Discuss knee walls as Attic section rather than Walls

### ISSUE THREAD

**Issue by brandongallagher** [hpxmlwg/hpxml#102]
Noel, I thought I'd bring this up for discussion...

At CakeSystems, we've struggled with handling knee walls in a simple way.  HPXML has considered them as wall sections, just like any other wall section, but that can be referenced internally by the particular attic that uses them.  This complexity seems technically accurate, but leads to a lot of confusing manipulations in the xml.

We have recently decided to just handle knee walls as pure attic sections rather than walls.  Instead of dealing specifically with the vertical wall part that is technically the kneewall, we're loosely considering the whole triangle that makes up what people generally consider the kneewall (slope, flat, and vertical wall).  Lumping them all into one thing, we can describe it simply as an attic slope/rafter rather than as the complex combination of separate parts.  

I hear Home Energy Score has recently come to the same decision with how they want to describe knee walls in their model.  

I wonder if we can come up with a recommended approach for handling these in HPXML.  That way Cake, HES, and other tools that want a simple option have a prescribed way to handle them in HPXML.  

Separately, I think this would be an issue to consider for NREL's HPXML->HES translator tool.

**Comment by GamalielL** [comment]
We have an ongoing discussion regarding a potential V3 reorganization of
the AtticAndRoof node to better handle they way multiple surfaces bounding
a single attic can be described.  This seems like another layer to add to
that discussion.

**Comment by nmerket** [comment]
Yeah, we need to get that discussion about attics going again. Knee walls are definitely an issue. 

@brandongallagher I wasn't aware HEScore was doing anything with knee walls. There currently aren't inputs for it and aren't any in v2016 either. @gmdickey, can you shed some light?

**Comment by gmdickey** [comment]
Our work around is to consider them as unconditioned attic floor area.  Since the assessor can enter an area and the conditions more closely approximate the attic than ambient, this should work reasonably well.

New email address: glenn.dickey@csra.com

Glenn Dickey
Senior Building Scientist
SRA International, Inc., A CSRA Company
6003 Executive Boulevard, #400
Rockville, MD 20852
240-514-2859 (desk)

**Comment by GamalielL** [comment]
From a modeling perspective, I agree that Glenn's approach is a good
workaround, provided that the knee walls a described separately with
appropriate construction and insulation details.  I think this is
preferable to translating it as an attic roof (as suggested by Brandon),
because it doesn't miss the important point that the surface is adjacent to
a buffer space rather than to ambient conditions.

From an HPXML perspective, I think the main issue is whether any programs
on the receiving end want to treat knee walls differently from attic
floors.  Hopefully we can find a way to rebuild the Attic node that
satisfies all of these needs.

**Comment by shorowit** [comment]
This is addressed by the [proposed attic refactor](https://github.com/hpxmlwg/hpxml/issues/28) for v3.

**Comment by Tedkidd** [comment]
Can the component be described by what boundary layer it is?

Some knee walls are thermal but not weather boundary, and possibly not even truly air boundary.
