### ISSUE TITLE
Remove "cape cod" from AtticType

### ISSUE THREAD

**Issue by nmerket** [hpxmlwg/hpxml#128]
With the addition of "conditioned attic" (#127) to [AtticType](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/AtticAndRoof/Attics/Attic/AtticType), I propose removing "cape cod" as "conditioned attic" is more general and explicit as to what it means.

**Comment by GamalielL** [comment]
I think "cape cod" is actually more explicit, because it is a particular
configuration of conditioned attic.  However, I think both are problematic,
because they describe a conditioned space and what we are listing with the
AtticAndRoof components are external boundaries. A conditioned attic space
will have several different external boundaries, such as roof deck, gable
wall, knee wall, or a small flat below the peak.  In addition there will be
small unconditioned attic buffer spaces behind knee walls and peak flats.
When we describe a surface that separates a conditioned attic space from an
unconditioned space, how should it be labeled.  I think the more important
relationship is to the unconditioned space.  If I were describing the flat
below a peak in a cape code, I would list it as AtticFloorInsulation with
an "unvented attic" Attic Type.

Maybe we should table these types of changes until we have hashed out the
restructuring of the attic node for V3.
ᐧ

**Comment by shorowit** [comment]
I agree that there are still some issues to resolve for v3 regarding external boundaries. But "cape cod" -> "conditioned attic" is a step in the right direction because cape cod refers to a style of home, not type of attic. It is also overly-specific, as it allows for so-called 1.5 story homes but excludes 2.5 story homes. Both 1.5 and 2.5 story could be described with conditioned attic.

**Comment by Tedkidd** [comment]
We have scopes for knee wall attics and attic flats. Agnostic about house type, doesn't really matter.
