### ISSUE TITLE
EV Chargers

### ISSUE THREAD

**Issue by juliecaracino** [hpxmlwg/hpxml#183]
Add Electric Vehicle Chargers (ENERGY STAR Certified)

Would this go under Building/Systems or under MiscLoads?

**Comment by nmerket** [comment]
@juliecaracino While related to #96, I think it's enough of its own thing that we should keep this open.

**Comment by Tedkidd** [comment]
EVSE's have different output limits, and car onboard AC to DC chargers have different outputs, and houses service and panels are going to have wildly varying free capacity for charging. 

My Smart I charged on 12a 110v - basically 1.2 kw. Took for ever, but it had so little range it didn't matter much. The on board charger could accept up to 3.3 kw.

My Bolt can take 7.5kw. 110 charging was insufficient. 

I ran 220 to the driveway and bought a Tesla HPWC that could go as high as 80 amp/20 kw and got an adapter for the Bolt. That was an amazing improvement.

Later I ran 100 amp service to the garage and have been charging the bolt at 3.2 kw, which seems to have been completely sufficient. 

The Tesla HPWC can charge the model 3 at 12 kw, which on rare occasion is really nice but mostly overkill. With a less efficient car or pickup truck I think charging at this rate or faster could be more important. 

Hope this is helpful...

**Comment by nmerket** [comment]
I reached out to our EV people and got a list of the following that we could include:

- Make
- Model
- Year installed
- Level 1 or Level 2 charger
- whether it can be scheduled or used in a DR event (pretty vague)

There should probably more. I just wanted to capture these somewhere.

**Comment by Tedkidd** [comment]
Good ideas. 

On the "Level" it might be more informative to provide KW capacity. 
Level 1 is going to be nearly irrelevant, and level 2 not very informative - Level 1 is basically 800-1200 watts, and level 2 can be anywhere from 2,000 to 20,000 watts. 

I currently have my EVSE's delivering 3000 and 12,000 watts (Bolt/Tesla). Most public chargers I've used deliver 6-7000.

Scheduling is probably best handled by the car

Some EVSE's are web enabled and could be used for DR or other grid services (maybe throttling - caltech has a parking garage they are doing all kinds of this research with). I'm dubious that the utilities will be willing to pay enough for it to spark much interest. I suspect TOU will be the effective motivator for car owners.

**Comment by Tedkidd** [comment]
Discussion today brought up connection type. For level 1 & 2 (home use) it's Tesla and J1772. 

There are adapters available that adapt tesla EVSE to j1772, and j1772 EVSE to tesla, making either type available to all cars. Not sure this matters other than FYI

MORE BACKGROUND:
For level 3 there are Tesla, CCS, and ChaDEmo. CCS looks like it'll be adopted by the most brands, Tesla will be the widest used (the most cars) by a factor of 10-100x. ChaDEmo (Nissan, Mitsubishi) has unique feature of being vtg ready. I can't imagine any of this applies to hpxml except the boutique maybe use of mitsubishi plug in hybrid for backup power to a house.

Tesla has a ChaDEmo adapter, and I suspect they will come out with a CCS adapter so the cars will be able to use any/all fast charging networks. 

Elon Musk has gone into detail about why vtg will not scale. I would never pay for the infrastructure, I can't imagine most people would, and the grid won't because the car probably won't be connected when the grid needs it. So I'm in agreement that it is a use that won't scale. But there may be something I'm not seeing.
