### ISSUE TITLE
Add Supply and Return Duct Static Pressures

### ISSUE THREAD

**Issue by juliecaracino** [hpxmlwg/hpxml#33]
Submitted by APS. Justification to follow.

**Comment by wmurphy67** [comment]
Should be careful defining supply and return statics. There are multiple locations within the supply or return where static can be measured. They can all be helpful. 

I assume the intent of this request might center on a specific supply and return pressure location in order to determine Total External Static Pressure (TESP).

However, a program may want to verify static pressure drop across filter where filter drop = return static pressure (location 1) minus return static pressure drop (location 2), or other types of calculations.

Suggest adding: 
 - a 'static pressure' measurement numerical field, which can be negative or positive
 - an associated question "Where is measurement taken" with enumerators 'supply side in ducts' ' supply side at equipment' ' return side at equipment' and 'return side in ducts'
 - another location question which is a text field, where someone can further explain (e.g., this measurement taken in the 'return side in ducts' was taken before the filter, or at the return grille, or wherever.
 - a "static pressure source" field, with enumerators "as measured" "per design report" or "per OEM documentation." Programs (and contractors) want to be able to compare what the design is calling for and compare it with commissioning / testing results.

**Comment by nmerket** [comment]
@juliecaracino, does @wmurphy67's recommendation meet the need? What was the original justification that was to follow?

**Comment by juliecaracino** [comment]
@nmerket 

I don't think APS ever followed up with this. It was their issue. I will send response by email, but they will need to follow up if they want this addressed.

**Comment by ChrisCBaker** [comment]
The original justification was simply to collect the TESP information. Supply and Return duct pressures typically at the plenum's. + numbers could denote supplies, - could point out returns. There should be room for multiple systems. When commissioning equipment, AC installers should be performing a TESP test and matching it with the blower performance chart for that AHU. We would like to see a field for that information to be stored within HPXML. At this time, our HPwES contractors collect that information, but even though it can be input in some modeling software, it is essentially a dead field because it ultimately does not end up in the HPxML. I would leave it very data field and allow the programs to determine where and how to take the tests.

**Comment by ChrisCBaker** [comment]
*Leave it as a simple data field...
